# Generated by Django 4.2.4 on 2023-11-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_api', '0002_item_item_number_item_price_user_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_number',
            field=models.IntegerField(default=111),
        ),
    ]
