# Generated by Django 4.2.4 on 2023-11-14 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_api', '0003_alter_user_mobile_number_alter_user_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='new_api.user'),
            preserve_default=False,
        ),
    ]
