# Generated by Django 4.2.4 on 2023-11-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_api', '0005_alter_item_user_customerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
